version: '3'
services:
  jpay-backend:
    container_name: jpay-backend
    ports:
      - 8080:8080
    build:
      context: JpayBE/
      dockerfile: Dockerfile
    image: jpay-backend:latest
  jpay-frontend:
    container_name: jpay-frontend
    ports:
      - 80:80
    build:
      context: jpayFE/
      dockerfile: Dockerfile
    image: jpay-frontend:latest

